import type { Metadata } from "next";
import "./globals.css";

import { Albert_Sans } from 'next/font/google'
const albertsans = Albert_Sans({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  display: 'swap'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albertsans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
